### ISSUE TITLE
Exported variable has or is using name from external module "expect-type/dist/index" but cannot be named

### ISSUE THREAD

**Issue by electrovir** [mmkal/expect-type#102]
Exporting types that depend on `expect-type` triggers this error... sometimes?

My example is is rather convoluted (involves multiple layers exports and a spread) but it happens right here: https://github.com/electrovir/augment-vir/blob/6d95efaedb6332ab75233057b45042b896823734/packages/assert/src/augments/guards/assert.ts#L6
![screenshot](https://github.com/user-attachments/assets/c6ce75b8-f5d0-42ed-8e2e-91697de2be4c)

## Solution

Luckily, the solution is very simple: `type Mismatch` and `type AValue` need to be exported in the package's `index.d.ts` file.

`Mismatch`: https://github.com/mmkal/expect-type/blob/35b0962811d941578a702e6298ef44aeb04990eb/src/utils.ts#L144

`AValue`: https://github.com/mmkal/expect-type/blob/35b0962811d941578a702e6298ef44aeb04990eb/src/utils.ts#L157

Interestingly, you'll see above that `Avalue` _is_ actually exported in the source code, but that's not the case in the published package. In the published `index.d.ts` file I see the following (note the lack of `export`):

```typescript
declare type AValue = {
    [avalue]?: undefined;
} | string | number | boolean | symbol | bigint | null | undefined | void;
```

**Comment by aryaemami59** [comment]
I was afraid this would happen, I'll take a look.

**Comment by aryaemami59** [comment]
Not sure if we're going to want to export those types in the future but for now you can you can use the new pre-release version and it should work. You can install it by running this in your cli:

```bash
npm install expect-type@next
```

**Comment by mmkal** [comment]
@electrovir what version are you using atm?

**Comment by electrovir** [comment]
This is on `0.19.0`. I just today upgraded from `0.15.0`.

**Comment by electrovir** [comment]
> ```shell
> npm install expect-type@next
> ```

This is working!

**Comment by mmkal** [comment]
Great. Happy to release 0.20.0-0 (i.e. `next`) as 0.20.0. But I'm actually a little unsure that it will fully solve this problem. There are still some types that depend on non-exported types. They might just only show up on failures since they involve `Mismatch`:

<img width="950" alt="image" src="https://github.com/user-attachments/assets/fd0bb75a-d616-4f5e-8126-ae9d70be9552">

@aryaemami59 given we are already exporting various utils and planning on marking as internal, want to just export these variables and types when you're adding the `@internal` tags to the jsdoc comments? I don't really see any additional harm in exporting `Mismatch` etc. when we're exporting other equally implementation-specific stuff already. Especially for v1, which I would like to be an official, stable version of what we currently have in v0. For v2 we could _consider_ getting more aggressive about not exporting any internals (that's another debate though).

**Comment by aryaemami59** [comment]
@mmkal I'm fine with exporting anything as long as you're okay with it. And yes I can go ahead and export the ones we need to export when I add the `@internal` tags. On a side note it seems like in this particular case exporting `MismatchArgs` also solves the issue which now that I think about it makes more sense considering the fact that `Mismatch` is not even exported in v0.20.0-0 yet the issue goes away when using v0.20.0-0.

**Comment by mmkal** [comment]
Released in [v0.20.0](https://github.com/mmkal/expect-type/releases/v0.20.0)

**Comment by electrovir** [comment]
I just tried `v0.20.0` and it's working just as `v0.20.0-0` was. Thank you!

**Comment by mmkal** [comment]
No problem - and thank you for the sponsorship!
