### ISSUE TITLE
`.toMatchTypeOf()` does not handle `Readonly` consistently

### ISSUE THREAD

**Issue by mrazauskas** [mmkal/expect-type#52]
[Playground link](https://www.typescriptlang.org/play?ts=5.3.3&ssl=5&ssc=1&pln=7&pc=1#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkaG2AtDAcnQNwBQ3jWudiQA8AJWQBDACYQAdgBs8wgM4wowWQHMA2gF0AfPoAUASgB0siDDMwIAWQkxMAC3xFiKtRp0HTPPugCbsgi4tJyisIOYJ7qWgA0cKpxmobG5pbWtg5OrkIe0bHeicnehn4BTILuYpIyCkoAysgwRVppphZWNvaOLsEiza2l7en+-NgDHmH1kUgSAFxJXlrk5Rnd2X15NfNLI5prFUA).

The `.toMatchTypeOf()` matcher treats `Readonly` array and map / set / object types differently:

```ts
import { expectTypeOf } from 'expect-type';

expectTypeOf<Readonly<string[]>>().not.toMatchTypeOf<string[]>();

// I would expect the following to pass as well, but they all error

expectTypeOf<Readonly<Map<string, string>>>().not.toMatchTypeOf<Map<string, string>>();
expectTypeOf<Readonly<Set<string>>>().not.toMatchTypeOf<Set<string>>();

expectTypeOf<Readonly<{ a: string }>>().not.toMatchTypeOf<{ a: string }>();
```

**Comment by mmkal** [comment]
For Map and Set, this is correct behaviour. You should use `ReadonlyMap<string, string>` instead of `Readonly<Map<string, string>>`. I believe typescript has a special case for arrays, where `Readonly<string[]>` is the same as `ReadonlyArray<string>`. [Fixed playground for Map and Set](https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkaG2AtDAcnQNwBQ3jWudiQA8AJWQBDACYQAdgBs8wgM4wowWQHMA2gF0AfPoAUASgB0siDDMwIAWQkxMAC3xFiKtRp0HTPPugCbsgi4tJyig5gnupaADRwqrGahqYWVjb2ji7BIlEx3glJ3qkmPPzYuR5hMgp4AMrIMAVapenWtg5OrkIejc3FrcZl3EA).

As for your `{a: string}` example - I agree that it's unfortunate that it passes, but it matches typescript's behaviour:

```ts
const readonlyObj: Readonly<{a: string}> = {a: 'a'}

readonlyObj satisfies {a: string}

const mutatingFn = (obj: {a: string}) => {
  obj.a = 'sorry not sorry'
}

mutatingFn(readonlyObj)
```

([playground](https://www.typescriptlang.org/play?ts=5.3.3&ssl=9&ssc=24&pln=1&pc=1#code/MYewdgzgLgBATgUwIYBNwBsCeB5ARgKwC4YAlZNMLAHgG8ljo4BLMAcwF8A+GAXhjuIByJIPYAoMYlQYcBGBCRQmEAGZMEEfvXlRmbcWNCRYAWwCuURS1YAxMLxgAKEAWICdejgEpe3GmJgYF3wAOiQHQQgQODhMGDAQWCiYzEExA3NLJTY7RykKLDx8LwkgA))

It don't think it would make sense to have expect-type deviate from typescript's behaviour here, but feel free to reference this issue in https://github.com/microsoft/typescript/issues - there is likely an existing issue for it.

**Comment by mrazauskas** [comment]
Apologies, the example could be better.

The current documentation suggests that `.toMatchTypeOf()` can be used "To allow for extra properties". At least this is how I understood description and example. It sounds like `.toMatchTypeOf()` is identical with `.toEqualTypeOf()`, but allows testing partial match. That seems to be incorrect, when `readonly` gets involved:

```ts
import { expectTypeOf } from 'expect-type';

expectTypeOf<{ readonly a: string; b: number }>().not.toEqualTypeOf<{ a: string; b: number }>();

expectTypeOf<{ readonly a: string; b: number }>().not.toMatchTypeOf<{ a: string }>(); // should also pass, but it fails
```

[playground](https://www.typescriptlang.org/play?ts=5.3.3#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkaG2AtDAcnQNwBQ3jWudiQA8SKMgCGAEwgA7ADZ44EgFxwAzjCjBZAc05wARmtkBXEIeRRyAPgAUASgB0siDCcwIAUQCOpifL4RMSiymqa2noGxnBmFla2jjx86AJByCJikjIKSqoaWjr6RibmltZk9s6u7p4AshIwmAAW6ZlhBZG6iQ4GAPR9Gs0QpvJSyvLqEHBgEurqADRGpvDA8MQSwJPcQA)

**Comment by mrazauskas** [comment]
> note that you can still call `.set(...)` etc. on `ReadonlyMap`s.

I guess you mean: `.set()` does not exist on `ReadonlyMap`, but `Readonly<Map<...>>` has it. That‘s right, `ReadonlyMap` must be used instead of `Readonly<Map<...>>`, because they are not identical.

`.toMatchTypeOf()` works correctly with `ReadonlyMap` or `ReadonlySet`. All of following does pass:

```ts
expectTypeOf<{ a: Map<string, number>; b: number }>().toMatchTypeOf<{ a: Map<string, number> }>();
expectTypeOf<{ a: ReadonlyMap<string, number>; b: number }>().not.toMatchTypeOf<{ a: Map<string, number> }>();

expectTypeOf<{ a: Set<string>; b: number }>().toMatchTypeOf<{ a: Set<string> }>();
expectTypeOf<{ a: ReadonlySet<string>; b: number }>().not.toMatchTypeOf<{ a: Set<string> }>();
```
