### ISSUE TITLE
How about check type of predicate with generic

### ISSUE THREAD

**Issue by linlinyang** [mmkal/expect-type#71]
``` typescript
const includes = <T>(arr: T[], val: unknow): val is T => arr.includes(val);
```
Is there any way test the predicate of `includes` function，`expectTypeOf(includes).guards` get `never` type, and `assertType(includes([1,2,3], 1))` just check return type but not predicate.

**Comment by aryaemami59** [comment]
`.guards` assumes the value that is being checked is the first parameter, also instead of checking `includes([1,2,3], 1)` you can use an instantiation expression, so it would look something like this:

```ts
const includes = <T>(val: any, arr: T[]): val is T => arr.includes(val)

expectTypeOf(includes<number>).guards.toBeNumber()
```

There are probably better ways to handle this, but off the top of my head this is what I could come up with.

**Comment by linlinyang** [comment]
@aryaemami59 Thanks.
